apiVersion: v1
kind: Pod
metadata: 
  name: posstgres-pod
  labels:
    type: db
    author: santhoshi
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: mypostgres
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
