apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    type: webserver
    author: santhoshi
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
         - containerPort: 80
           hostPort: 80

